import type { Metadata } from "next";
import { getSession } from "@/auth";
import { AuthProvider } from "@/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto">
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
}
