/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AidesigntoolUsers {
  email: string;
  id: Generated<number>;
  name: string | null;
  password: string | null;
}

export interface AidesigntoolUsersBalances {
  balance: number;
  user_id: number;
}

export interface DB {
  "aidesigntool.users": AidesigntoolUsers;
  "aidesigntool.users_balances": AidesigntoolUsersBalances;
}
